title: Phương Kể
description: Let me show you the world in my eyes.
url: "https://mpstories.github.io/"

theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives

# Enable categories and tags
collections:
  posts:
    output: true
    permalink: /:categories/:year/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true

# Archives for categories/tags
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

  
  
