title: Phương Kể
description: Let me show you the world in my eyes.

theme: minima # GitHub Pages supports this by default

permalink: /:year/:month/:day/:title/
markdown: kramdown

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude these from the build
exclude:
  - README.md
